Name:           ros-indigo-webargs
Version:        1.3.4
Release:        1%{?dist}
Summary:        ROS webargs package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-marshmallow >= 2.0.0
BuildRequires:  python-bottle
BuildRequires:  python-falcon
BuildRequires:  python-mock
BuildRequires:  python-pyramid
BuildRequires:  python-pytest
BuildRequires:  python-webtest
BuildRequires:  ros-indigo-catkin >= 0.6.18
BuildRequires:  ros-indigo-catkin-pip >= 0.1.15
BuildRequires:  ros-indigo-marshmallow >= 2.0.0

%description
A friendly library for parsing HTTP request arguments, with built-in support for
popular web frameworks, including Flask, Django, Bottle, Tornado, Pyramid,
webapp2, Falcon, and aiohttp.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Sep 05 2016 AlexV <asmodehn@gmail.com> - 1.3.4-1
- Autogenerated by Bloom

* Mon Sep 05 2016 AlexV <asmodehn@gmail.com> - 1.3.4-0
- Autogenerated by Bloom

